dict1/config/routes.rb
Dict1::Application.routes.draw do
  resources :dictionaries

end

dict1/app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
end

dict1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

dict1/app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dictionary }
      else
        format.html { render action: 'new' }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictionary_params
      params.require(:dictionary).permit(:word_en, :word_other, :know, :dont_know, :not_sure)
    end
end

dict1/app/helpers/application_helper.rb
module ApplicationHelper
end

dict1/app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

dict1/app/views/dictionaries/_form.html.erb
<%= form_for(@dictionary) do |f| %>
  <% if @dictionary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dictionary.errors.count, "error") %> prohibited this dictionary from being saved:</h2>

      <ul>
      <% @dictionary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word_en %><br>
    <%= f.text_field :word_en %>
  </div>
  <div class="field">
    <%= f.label :word_other %><br>
    <%= f.text_field :word_other %>
  </div>
  <div class="field">
    <%= f.label :know %><br>
    <%= f.check_box :know %>
  </div>
  <div class="field">
    <%= f.label :dont_know %><br>
    <%= f.check_box :dont_know %>
  </div>
  <div class="field">
    <%= f.label :not_sure %><br>
    <%= f.check_box :not_sure %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dict1/app/views/dictionaries/edit.html.erb
<h1>Editing dictionary</h1>

<%= render 'form' %>

<%= link_to 'Show', @dictionary %> |
<%= link_to 'Back', dictionaries_path %>

dict1/app/views/dictionaries/index.html.erb
<h1>Listing dictionaries</h1>

<table>
  <thead>
    <tr>
      <th>Word en</th>
      <th>Word other</th>
      <th>Know</th>
      <th>Dont know</th>
      <th>Not sure</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dictionaries.each do |dictionary| %>
      <tr>
        <td><%= dictionary.word_en %></td>
        <td><%= dictionary.word_other %></td>
        <td><%= dictionary.know %></td>
        <td><%= dictionary.dont_know %></td>
        <td><%= dictionary.not_sure %></td>
        <td><%= link_to 'Show', dictionary %></td>
        <td><%= link_to 'Edit', edit_dictionary_path(dictionary) %></td>
        <td><%= link_to 'Destroy', dictionary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dictionary', new_dictionary_path %>

dict1/app/views/dictionaries/new.html.erb
<h1>New dictionary</h1>

<%= render 'form' %>

<%= link_to 'Back', dictionaries_path %>

dict1/app/views/dictionaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word en:</strong>
  <%= @dictionary.word_en %>
</p>

<p>
  <strong>Word other:</strong>
  <%= @dictionary.word_other %>
</p>

<p>
  <strong>Know:</strong>
  <%= @dictionary.know %>
</p>

<p>
  <strong>Dont know:</strong>
  <%= @dictionary.dont_know %>
</p>

<p>
  <strong>Not sure:</strong>
  <%= @dictionary.not_sure %>
</p>

<%= link_to 'Edit', edit_dictionary_path(@dictionary) %> |
<%= link_to 'Back', dictionaries_path %>