lang/config/routes.rb
Lang::Application.routes.draw do
  resources :languages do
    resources :words
end

end

lang/app/models/language.rb
class Language < ActiveRecord::Base
has_many :words
end

lang/app/models/word.rb
class Word < ActiveRecord::Base
belongs_to :language
end

lang/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lang/app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render action: 'show', status: :created, location: @language }
      else
        format.html { render action: 'new' }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:lang_a, :lang_b)
    end
end

lang/app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @language_words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @language_word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @language_word = Word.new(word_params)

    respond_to do |format|
      if @language_word.save
        format.html { redirect_to @language_word, notice: 'Word was successfully created.' }
        format.json { render action: 'show', status: :created, location: @language_word }
      else
        format.html { render action: 'new' }
        format.json { render json: @language_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @language_word.update(word_params)
        format.html { redirect_to @language_word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @language_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @language_word.destroy
    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @language_word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word_a, :word_b, :know)
    end
end

lang/app/helpers/application_helper.rb
module ApplicationHelper
end

lang/app/helpers/languages_helper.rb
module LanguagesHelper
end

lang/app/helpers/words_helper.rb
module WordsHelper
end

lang/app/views/languages/_form.html.erb
<%= form_for(@language) do |f| %>
  <% if @language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% @language.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lang_a %><br>
    <%= f.text_field :lang_a %>
  </div>
  <div class="field">
    <%= f.label :lang_b %><br>
    <%= f.text_field :lang_b %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lang/app/views/languages/edit.html.erb
<h1>Editing language</h1>

<%= render 'form' %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

lang/app/views/languages/index.html.erb
<h1>Listing languages</h1>

<table>
  <thead>
    <tr>
      <th>Lang a</th>
      <th>Lang b</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.lang_a %></td>
        <td><%= language.lang_b %></td>
        <td><%= link_to 'Add words', new_language_word_path(language) %></td>
        <td><%= link_to 'Show', language %></td>
        <td><%= link_to 'Edit', edit_language_path(language) %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Language', new_language_path %>

lang/app/views/languages/new.html.erb
<h1>New language</h1>

<%= render 'form' %>

<%= link_to 'Back', languages_path %>

lang/app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lang a:</strong>
  <%= @language.lang_a %>
</p>

<p>
  <strong>Lang b:</strong>
  <%= @language.lang_b %>
</p>

<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>